import type { NextPage } from "next";

import Head from "next/head";
import React, { useState } from "react";
import CalculatorForm from "../components/calculator-form";
import Page from "../components/page";
import ProductList from "../components/product-list";
import { DateRange } from "../data/enums";

export interface CalculatorState {
  price: number;
  hours: number;
  range: DateRange;
}

const Home: NextPage = () => {
  const [state, setState] = useState<CalculatorState>({
    price: 35,
    hours: 1,
    range: DateRange.Day,
  });

  return (
    <>
      <Head>
        <title>Energikalkylator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <h1>
          Räkna på din <span>elkostnad</span>
        </h1>
        <p>Hur mycket kostar elektroniken i hushållet?</p>
        <CalculatorForm
          state={state}
          onChange={(state: any) => {
            setState(state);
          }}
        />
        <ProductList state={state} />
      </Page>
    </>
  );
};

export default Home;
